version: "3.8"
services:
  back-end:
    container_name: hello_world
    image: hello_world:latest
    build: ./application
    ports:
    - target: 5000
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf